# 基础信息
itzy-micro-service:
  local: localhost
  hosts:
    api-gateway: ${itzy-micro-service.local}
    eureka-service: ${itzy-micro-service.local}
    config-service: ${itzy-micro-service.local}
# MySQL
DB_HOST: ${itzy-micro-service.local}
DB_PASS: root
# Redis
REDIS_HOST: ${itzy-micro-service.local}
REDIS_DB: 1
#RabbitMQ
RABBITMQ_HOST: ${itzy-micro-service.local}
# MongoDB
#MONGODB_HOST: dev.mongodb.i.sixi.com